### ISSUE TITLE
poi outside boundaries of polygon

### ISSUE THREAD

**Issue by RafaRafa** [jolars/polylabelr#5]
I have a polygon (saved here: https://pastebin.com/QpKFVgfy) 

If I run: 

`poi(x$long, x$lat)
`
It looks like it's putting the point outside boundaries:
![Rplot11](https://user-images.githubusercontent.com/8324171/81882005-a02da880-955f-11ea-98bf-fef5470c0e20.png)

**Comment by jolars** [comment]
Well that's because it's treating all the coordinates as a single polygon. `poi()` cannot possible know that you have several distinct polygons in your coordinates. You need to run the function for each polygon separately or provide a data.frame with NA rows separating the coordinates into several polygons.
