### ISSUE TITLE
Multipart polygon question

### ISSUE THREAD

**Issue by jmw86069** [jolars/polylabelr#7]
Hi, I love this package: simple, useful, effective!

I like that it works with polygons having holes, even nested parts inside a hole for example.

However, I noticed with multi-part polygons, it just uses the first polygon.
For example, simple test case with two-part squares:
```R
testxy <- data.frame(
   x=c(0, 10, 10, 0, NA, 15, 16, 16, 15),
   y=c(0, 0, 10, 10, NA, 0, 0, 1, 1))
plot(testxy, type="l", asp=1)
polypath(testxy, col=c("red4"))
points(polylabelr::poi(x=testxy$x, y=testxy$y), pch=20, col="gold", cex=4)
```
<img width="623" alt="image" src="https://github.com/user-attachments/assets/2b363a24-36c4-44c9-94cf-98b72ed10ee6">

Works as expected.

However, if the squares are reversed, it picks the first one, having smallest area:
```R
testxy2 <- data.frame(
   x=c(15, 16, 16, 15, NA, 0, 10, 10, 0),
   y=c(0, 0, 1, 1, NA, 0, 0, 10, 10))
plot(testxy2, type="l", asp=1)
polypath(testxy2, col=c("blue4"))
points(polylabelr::poi(x=testxy2$x, y=testxy2$y), pch=20, col="gold", cex=4)
```
<img width="621" alt="image" src="https://github.com/user-attachments/assets/297793e7-9cf1-4d35-adf6-cc22e6e94283">

So... is this expected?

I have a workaround myself - use the polygon with largest area. But I'm sure there are polygons "not ideal" for labeling which have large total area. Like tall-skinny (not ideal) and circular (ideal) with similar areas.

Not urgent, mainly wanted to say nice R package, and see if you had an opinion.

**Comment by jolars** [comment]
Thanks for the report! I'll try to fix this during the week. It's time I update mapbox headers as well.

**Comment by jolars** [comment]
I guess the "bug" part here really is that the multi-polygon isn't understood as that by polylabelr (and by etension mapbox/polylabel). So to work around this we need to loop over all the rings in the input and decompose that into a multipolygon object with disjoint polygons and then for each polygon compute the POI and return the one with the largest distance. But in some sense I guess this isn't that much of a bug since the input is not really as expected. 

I guess there could be some computational concerns here because we need to walk over all combinations of these rings. I'm not completely sure we want to cater to this.

What does your input look like here, by the way? I suppose you know that you have a multi-polygon, right? Would it be fine to have a new function, say `multi_poi()` that expects a multi-polygon, i.e. a list of polygons? This would simplify the implementation a lot because there would be no need to compute intersections between the rings.

**Comment by jolars** [comment]
Yes, actually this is exactly what we are already doing in `poi.MULTIPOLYGON()` (for the method for the respective simple features class. So let's just use that.
